/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3-rc-1/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "title"

include(":api")

include(":v1_8_R3")
project(":v1_8_R3").projectDir = file("version/v1_8_R3")

include(":v1_12_R1")
project(":v1_12_R1").projectDir = file("version/v1_12_R1")

include(":v1_14_R1")
project(":v1_14_R1").projectDir = file("version/v1_14_R1")

include(":v1_16_R3")
project(":v1_16_R3").projectDir = file("version/v1_16_R3")